name: build-snapshot
on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  buildSnapshot:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out source code
        uses: actions/checkout@v3
      - name: Setting up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '21'
          overwrite-settings: true
      - name: Installing dependencies and creating jar
        run: mvn clean install
      - name: Deploying snapshot to packages
        run: |
          echo "<settings><servers><server><id>deployment</id><username>anjaneyalndatla</username><password>${GITHUB_TOKEN}</password></server></servers></settings>" > ~/.m2/settings.xml
          mvn deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}