name: release
on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: "Version to release (major.minor.patch)"
        required: true
      developmentVersion:
        description: "Next development version (major.minor.patch)"
        required: true
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Maven Release
        run: | 
          echo "<settings><servers><server><id>deployment</id><username>anjaneyalndatla</username><password>${GITHUB_TOKEN}</password></server></servers></settings>" > ~/.m2/settings.xml
          mvn release:prepare release:perform -B -DreleaseVersion=${{ github.event.inputs.releaseVersion }} -DdevelopmentVersion=${{ github.event.inputs.developmentVersion }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  