name: release
on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: "Version to release (major.minor.patch)"
        required: true
      developmentVersion:
        description: "Next development version (major.minor.patch)"
        required: true
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checking out source code
        uses: actions/checkout@v3
        env:
          token: ${{ secrets.PAT_TOKEN }}
      - name: Setting up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '21'
      - name: Temporary commit
        run: | 
          git config user.email ${GITHUB_ACTOR}@gmail.com
          git config user.name ${GITHUB_ACTOR}
          git config --list
          echo "hello 2" > test.yml
          git add .
          git commit -m "test"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
          GITHUB_ACTOR: ${{ github.actor }}
      # - name: Maven Release
      #   run: | 
      #     echo "<settings><servers><server><id>deployment</id><username>anjaneyalndatla</username><password>${GITHUB_TOKEN}</password></server></servers></settings>" > ~/.m2/settings.xml
      #     echo "Actor -- ${GITHUB_ACTOR}"
      #     git config user.email ${GITHUB_ACTOR}@gmail.com
      #     git config user.name ${GITHUB_ACTOR}
      #     git config --list
      #     mvn release:prepare release:perform -B -DreleaseVersion=${{ github.event.inputs.releaseVersion }} -DdevelopmentVersion=${{ github.event.inputs.developmentVersion }}
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
      #     GITHUB_ACTOR: ${{ github.actor }}
  
