name: release
on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: "Version to release (major.minor.patch)"
        required: true
      developmentVersion:
        description: "Next development version (major.minor.patch)"
        required: true
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out source code
        uses: actions/checkout@v3
      - name: Setting up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '21'
          overwrite-settings: true
      - name: Configure Git User
        run: |
          git config user.email ${GITHUB_ACTOR}@gmail.com
          git config user.name ${GITHUB_ACTOR}
        env:
          GITHUB_ACTOR: ${{ github.actor }}

      - name: Maven Release
        run: | 
          echo "<settings><servers><server><id>deployment</id><username>anjaneyalndatla</username><password>${GITHUB_TOKEN}</password></server></servers></settings>" > ~/.m2/settings.xml
          mvn release:prepare release:perform -B -DreleaseVersion=${{ github.event.inputs.releaseVersion }} -DdevelopmentVersion=${{ github.event.inputs.developmentVersion }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTOR: ${{ github.actor }}
  